#!/usr/bin/env python3

#*****************************************************************************
#  Name: SVJedi-Tag
#  Description: Genotyping of SVs with linked-reads data
#  Copyright (C) 2025 INRIA
#  Author: Anne Guichard, Mélody Temperville
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#*****************************************************************************

"""
Module 'svjedi-tag.py': Pipeline of SVJedi-Tag.
"""

import sys
import argparse
import os
import re
import subprocess


#pylint: disable=line-too-long, disable=trailing-whitespace, disable=consider-using-f-string


def main(args):

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "-v", 
        "--vcf", 
        metavar="VCF file containing the target inversions to genotype.", 
        type=str,
        required=True)

    parser.add_argument(
        "-r", 
        "--reference", 
        metavar="Reference genome file.", 
        type=str, 
        required=True)

    parser.add_argument(
        "-q", 
        "--linked_reads", 
        metavar="Interleaved linked-read FASTQ file or two paired-end FASTQ files", 
        type=str, 
        required=True,
        nargs="+")

    parser.add_argument(
        "-p", 
        "--prefix", 
        metavar="Output path and/or prefix", 
        type=str, 
        required=True)

    parser.add_argument(
        "-t", 
        "--threads", 
        metavar="Number of threads", 
        type=int, 
        default=1)

    parser.add_argument(
        "-s",
        "--regionSize",
        metavar="Signal barcode region size (default = 10kp).",
        type=int,
        required=False,
        default=10000)

    parser.add_argument(
        "-a", 
        "--gaf", 
        metavar="GAF alignment file of linked reads against the graph (output of vg giraffe).", 
        type=str,
        required=False)
    
    parser.add_argument(
        "-g", 
        "--gfa", 
        metavar="GFA graph file generated by SVJedi-Tag.", 
        type=str,
        required=False)
    
    parser.add_argument(
        "-i",
        "--inaccuracy",
        metavar="Breakpoint inaccuracy tolerance (bp).",
        type=int,
        required=False,
        default = 0)
    
    parser.add_argument(
        "-d", 
        "--likelihood_min_diff", 
        metavar="Minimum difference between the two bigger genotype likelihood.", 
        type=int,
        nargs=1,
        required=False,
        default=20)

    args = parser.parse_args()
    inVCF = args.vcf
    inREF = args.reference
    inFQ = args.linked_reads
    outPrefix = args.prefix
    threads = args.threads
    regionSize = args.regionSize
    bk_inaccuracy = args.inaccuracy
    diff_treshold = args.likelihood_min_diff

    script_path = os.path.abspath(__file__)
    script_dir = os.path.dirname(script_path)

    if args.gaf or args.gfa :
        if not args.gaf : 
            print('### Gaf file (alignement) necessary please use parameter --gaf ###')
            
        if not args.gfa : 
            print('### Gfa file (graphe) necessary please use parameter --gfa ###')
            
        else:
            print("### Mapping of linked-reads onto graph already done ###")
            outGAF = os.path.abspath(args.gaf)
            outGFA = os.path.abspath(args.gfa)
            print("Alignment GAF file: " + str(outGAF))

            #### Analyze barcode signal & Genotype.
            print("### Analyze barcode signal & Genotype ###")
            outVCF = outPrefix + "_genotype.vcf"
            c6 = "python3 {}/predict_genotype.py -a {} -v {} -o {} -s {} -g {}".format(script_dir, outGAF, inVCF, outVCF,regionSize, outGFA)
            subprocess.run(c6, shell=True, check=True)
        
    else:
        #### Create variant graph.
        print("### Create variant graph ###")
        outGFA = outPrefix + ".gfa"
        c1 = "python3 {}/construct_graph.py -v {} -r {} -o {}".format(script_dir,inVCF, inREF, outGFA)
        subprocess.run(c1, shell=True, check=True)

        # ### Index graph.
        # print("### Index graph ###")
        # c3 = "vg autoindex --workflow giraffe -g {} -p {}".format(outGFA, outPrefix)
        # subprocess.run(c3, shell=True, check=True)

        # ### Map linked-reads on graph.
        # print ("### Map linked-reads on graph ###")
        # outGBZ = outPrefix + ".giraffe.gbz"
        # outMIN = outPrefix + ".min"
        # outDIST = outPrefix + ".dist"
        # outGAF = outPrefix + "_vgGiraffe.gaf"

        # #if multifile == False :
        # if len(inFQ) == 2 :
        #     c4 = "vg giraffe -t {} -Z {} -m {} -d {} -f {} -f {} -o gaf --named-coordinates > {}".format(threads, outGBZ, outMIN, outDIST, inFQ[0],  inFQ[1], outGAF)
        # elif len(inFQ) == 1 :
        #     c4 = "vg giraffe -t {} -Z {} -m {} -d {} -f {} -i -o gaf --named-coordinates > {}".format(threads, outGBZ, outMIN, outDIST,inFQ[0], outGAF)
        # else:
        #     print("ERROR: Reads file required. One interleaved FASTQ or two paired-end FASTQ files.")
        #     exit(1)
        # subprocess.run(c4, shell=True, check=True)

        ### Index graph.
        print("### Index graph ###")

        c3 = "vg autoindex --workflow sr-giraffe -g {} -p {}".format(
            outGFA,
            outPrefix
        )

        subprocess.run(c3, shell=True, check=True)


        ### Map linked-reads on graph.
        print("### Map linked-reads on graph ###")

        outGBZ = outPrefix + ".giraffe.gbz"
        outMIN = outPrefix + ".shortread.withzip.min"
        outZIP = outPrefix + ".shortread.zipcodes"
        outDIST = outPrefix + ".dist"
        outGAF = outPrefix + "_vgGiraffe.gaf"


        if len(inFQ) == 2:

            c4 = (
                "vg giraffe "
                "-t {} "
                "-Z {} "
                "-m {} "
                "-z {} "
                "-d {} "
                "-f {} "
                "-f {} "
                "-o gaf "
                "--named-coordinates "
                "> {}"
            ).format(
                threads,
                outGBZ,
                outMIN,
                outZIP,
                outDIST,
                inFQ[0],
                inFQ[1],
                outGAF
            )

        elif len(inFQ) == 1:

            c4 = (
                "vg giraffe "
                "-t {} "
                "-Z {} "
                "-m {} "
                "-z {} "
                "-d {} "
                "-f {} "
                "-i "
                "-o gaf "
                "--named-coordinates "
                "--comments-as-tags " # to keep tag
                "> {}"
            ).format(
                threads,
                outGBZ,
                outMIN,
                outZIP,
                outDIST,
                inFQ[0],
                outGAF
            )

        else:
            print(
                "ERROR: Reads file required. "
                "One interleaved FASTQ or two paired-end FASTQ files."
            )
            exit(1)

        subprocess.run(c4, shell=True, check=True)

        #### Analyze barcode signal & Genotype.
        print("### Analyze barcode signal & Genotype ###")
        outVCF = outPrefix + "_genotype.vcf"
        c6 = "python3 {}/predict_genotype.py -a {} -v {} -o {} -s {} -g {} -i {} -d {}".format(script_dir, outGAF, inVCF, outVCF,regionSize, outGFA, bk_inaccuracy,diff_treshold)
        subprocess.run(c6, shell=True, check=True)


if __name__ == "__main__":
    if sys.argv == 1:
        sys.exit("Error: missing arguments")

    else:
        main(sys.argv[1:])
